---
title: "Homework 5"
author: "Christian Munger"
date: "4/15/2021"
output: 
  pdf_document: 
    latex_engine: xelatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}

Msft <- read.csv("C:\\Users\\cmunger\\OneDrive\\Risk Theory\\MSFT.csv")
Facebook <- read.csv("C:\\Users\\cmunger\\OneDrive\\Risk Theory\\FB.csv")

Msft.prices <- Msft$Adj.Close
Facebook.prices <- Facebook$Adj.Close

Msft.rets = -diff(Msft.prices)/Msft.prices[-length(Msft.prices)] # get arith rets
Facebook.rets = -diff(Facebook.prices)/Facebook.prices[-length(Facebook.prices)] # get arith rets



#P5

weighted <- c(.75, .25)

#a.
cov.matrix <- matrix(data = c(cov(cbind(Msft.rets,Facebook.rets))), nrow = 2, ncol = 2)
cov.matrix


#b(1 through 5)
variance <- t(weighted)%*%cov.matrix%*%weighted
variance



#Value at Risk
VaR <- 1000*sqrt(variance)*1.645
VaR






#Individual VaR's
VaR1 <- 750*sqrt(0.0003023717)*1.645
VaR1

VaR2 <- 250*sqrt(0.0004148669)*1.645
VaR2





#Undiversified VaR
VaR1 + VaR2   #Undiversified <= Diversified





#Beta vector
B_i <- (1/0.0002804439)*(cov.matrix%*%weighted)
B_i
#So, B1 = 1.0093495 and B2 = 0.9719521






#Marginal VaR vector

delta.VaR_i <- 1.645*sqrt(0.0002804439)*B_i
delta.VaR_i

#So, delta.VaR_1 = 0.02780548 and delta.VaR_2 = 0.02677527




#c.

incremental.VaR <- -10*0.02780549 + 5*0.02677527
incremental.VaR


#d.
W.star.2 <- (0.0002251484*750)/0.0004148669
W.star.2

new.VaR <- (750 + W.star.2)*sqrt(0.0002804439)*1.645
new.VaR
```

